# -*- coding: utf-8 -*-
"""002Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cWiM9a7yD88B2nqivCi3GrpiRurZghGp

###Analisis Sektor
##Membandingkan Performa Saham Berdasarkan sektor
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/DaftarSaham.csv')
df

df.info()

df.Sector

#menghitung Agregasi Per Sektor : Menghitung total nilai per Sektor
group = df.groupby('Sector').sum()
print(group)

#Mengiterasi Melalui Setiap Group
grouped = df.groupby('Sector')

for name, group in grouped:
    print(f'Sektor: {name}')
    print(group)

#Market_Sektor = df[df['Sector'] == 'Nama']
#print(Market_Sektor)

#menghitung Rata-rata, Median, dan standar deviasi Harga saham dan Kapitalisasi Pasar
statistic_Desc = df.groupby('Sector').agg(
    LastPrice_mean=('LastPrice', 'mean'),
    LastPrice_median=('LastPrice', 'median'),
    LastPrice_std=('LastPrice', 'std'),
    MarketCap_mean=('MarketCap', 'mean'),
    MarketCap_median=('MarketCap', 'median'),
    MarketCap_std=('MarketCap', 'std')
).reset_index()

print(statistic_Desc)

"""###Viasualisasi Perbandingan Performa antar Sector

##BarPlot Rata2 Harga Saham PerSektor
"""

plt.figure(figsize=(22,6))
sns.barplot(x='Sector', y='LastPrice_mean', data= statistic_Desc)
plt.title('Rata-rata Harga Saham /Sector')
plt.xlabel('Sector')
plt.ylabel('Rata-rata Harga Saham')
plt.show()

"""##Kapitalisasi Pasar /sector"""

plt.figure(figsize=(22,6))
sns.barplot(x='Sector', y='MarketCap_mean', data= statistic_Desc )
plt.title('Rata-rata Kapitalisasi Pasar /Sector')
plt.xlabel('Sector')
plt.ylabel('Rata-rata Kapitalisasi Pasar')
plt.show()

"""###Box Plot Distribusi Harga Saham Per Sector

"""

plt.figure(figsize=(20,6))
sns.boxplot(x='Sector', y='LastPrice', data=df)
plt.title('Distribusi Harga Saham/Sector')
plt.xlabel('Sector')
plt.ylabel('Harga Saham')
plt.show()

plt.figure(figsize=(20,6))
sns.boxplot(x='Sector', y='MarketCap', data=df)
plt.title('Distribusi Kapitalisasi Pasar/Sector')
plt.xlabel('Sector')
plt.ylabel('MarketCap')
plt.show()

"""###Scatter Plot
##Hubungan antara Harga Saham dan Kapitalisasi Pasar per Sector

"""

plt.figure(figsize=(20,6))
sns.scatterplot(x='LastPrice', y='MarketCap', hue='Sector', data=df)
plt.title('Hubungan Saham dan Kapitalisasi Pasar /Sector')
plt.xlabel('Harga Saham')
plt.ylabel('Kapitalisasi Pasar')
plt.legend(title=('Sector'))
plt.show()

